model:
  in_dim: 256
  hidden_dim: 256
  out_dim: 276
  n_heads: 8
  n_layers: 2
  in_feat_dropout: 0.1
  dropout: 0.4
  layer_norm: false
  batch_norm: true
  residual: true
  lap_pos_enc: true
  pos_enc_dim: 10

training:
  epochs: 100
  batch_size: 2
  learning_rate: 0.0001
  checkpoint_every: 50

clustering:
  distance_threshold: 0.65
